### ISSUE TITLE
Concurrency issue with aws-sdk-go/service/s3/s3manager

### ISSUE THREAD

**Issue by PaulMakepeace** [colinmarc/hdfs#187]
I've noticed it's necessary to dial the concurrency setting with [AWS's s3manager.Uploader](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#Uploader) to 1 in order for it to work. I'm guessing it's (ab)using `hdfs.FileReader` in some way.

Here's some code that consistently reproduces the issue,

```go
package main

// Environment variables:
// AWS_ACCESS_KEY_ID=
// AWS_SECRET_ACCESS_KEY=
// AWS_REGION=  # e.g. us-west-1
// AWS_KEY=  # e.g. tmp_large_file
// HDFS_FILE=  # defaults to /tmp/large_file

import (
	"log"
	"os"

	hdfs "github.com/colinmarc/hdfs/v2"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3/s3manager"
)


func main() {
	// Create a ~67M temporary file in HDFS
	// dd if=/dev/urandom of=/tmp/large_file bs=1000 count=67890
	// sudo -u hdfs hdfs dfs -put /tmp/large_file /tmp/

	// Connect to HDFS and open the file
	var hdfsFile = "/tmp/large_file"
	if _, ok := os.LookupEnv("HDFS_FILE"); ok {
		hdfsFile = os.Getenv("HDFS_FILE")
	}
	client, err := hdfs.New(os.Getenv("HADOOP_NAMENODE"))
	if err != nil {
		log.Fatal(err)
	}
	file, err := client.Open(hdfsFile)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	// Connect to S3
	sess := session.Must(session.NewSession(&aws.Config{
		Region:           aws.String(os.Getenv("AWS_REGION")),
	}))
	// Create an uploader with the session and (nearly) default options
	uploader := s3manager.NewUploader(sess, func(u *s3manager.Uploader) {
		u.Concurrency = 10 // 1 works
	})
	// Copy hdfsFile to S3
	var s3Path = os.Getenv("AWS_KEY")
	var s3Bucket = os.Getenv("AWS_BUCKET")
	result, err := uploader.Upload(&s3manager.UploadInput{
		Bucket: &s3Bucket,
		Key:    &s3Path,
		Body:   file,
	})
	if err != nil {
		log.Fatalf("failed to upload S3 file=%s/%s: %v", s3Bucket, s3Path, err)
	} else {
		log.Printf("S3 file uploaded to %s\n", result.Location)
	}
}
```

I've seen three errors: a SHA mismatch, unable to compute the hash at all, panics.

Here are some examples,

SHA mismatch,

```
failed to upload S3 file=anewbucket/tmp_large_file: MultipartUpload: upload multipart failed
        upload id: c7f25ce0-83cb-11e9-a486-248a078d2f04
caused by: 403: The SHA-256 of the request body did not match the value in x-amz-content-sha256. Server computed SHA-256 does not match SHA-256 from request: 370581648049DE577EDDBDCF88704EA04DB68902CA72302207034D5BB5F66AF0
        status code: 403, request id: , host id: 
```

Hash computation failure,

```
failed to upload S3 file=anewbucket/tmp_large_file: MultipartUpload: upload multipart failed
        upload id: 7d5a4090-83ca-11e9-a8c7-248a078d4b24
caused by: BodyHashError: failed to compute body hashes
caused by: io: read/write on closed pipe
```

Panic,

```
panic: runtime error: index out of range

goroutine 118 [running]:
github.com/colinmarc/hdfs/v2/internal/rpc.(*datanodeFailover).next(0xc000875900, 0xc0004f5180, 0xc000875900)
        /Users/makepeace/go/pkg/mod/github.com/colinmarc/hdfs/v2@v2.0.0/internal/rpc/datanode_failover.go:58 +0x4a9
github.com/colinmarc/hdfs/v2/internal/rpc.(*BlockReader).connectNext(0xc0002510a0, 0xc000875900, 0xc000999ce0)
        /Users/makepeace/go/pkg/mod/github.com/colinmarc/hdfs/v2@v2.0.0/internal/rpc/block_reader.go:131 +0x47
github.com/colinmarc/hdfs/v2/internal/rpc.(*BlockReader).Read(0xc0002510a0, 0xc0004ab000, 0x1000, 0x1000, 0xc0000e4100, 0xc0008db9d8, 0x9a2400)
        /Users/makepeace/go/pkg/mod/github.com/colinmarc/hdfs/v2@v2.0.0/internal/rpc/block_reader.go:86 +0x98
github.com/colinmarc/hdfs/v2.(*FileReader).Read(0xc000a54700, 0xc0004ab000, 0x1000, 0x1000, 0x101d, 0x0, 0x0)
        /Users/makepeace/go/pkg/mod/github.com/colinmarc/hdfs/v2@v2.0.0/file_reader.go:198 +0x201
io.ReadAtLeast(0xd06fc0, 0xc000a54700, 0xc0004ab000, 0x1000, 0x1000, 0x1000, 0xc00004e588, 0xc00083cf00, 0xc0006d6040)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:329
github.com/colinmarc/hdfs/v2.(*FileReader).ReadAt(0xc000a54700, 0xc0004ab000, 0x1000, 0x1000, 0xf52000, 0xc0006d6040, 0x5f0633, 0xc0008dbab8)
        /Users/makepeace/go/pkg/mod/github.com/colinmarc/hdfs/v2@v2.0.0/file_reader.go:229 +0x1da
io.(*SectionReader).Read(0xc0008086f0, 0xc0004ab000, 0x1000, 0x1000, 0x0, 0x0, 0xc000501a58)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:475 +0x78
github.com/aws/aws-sdk-go/aws/request.(*offsetReader).Read(0xc0002901e0, 0xc0004ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /Users/makepeace/go/pkg/mod/github.com/aws/aws-sdk-go@v1.19.39/aws/request/offset_reader.go:44 +0xe3
net/http.transferBodyReader.Read(0xc0004465a0, 0xc0004ab000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/net/http/transfer.go:62 +0x56
io.(*LimitedReader).Read(0xc0003a4340, 0xc0004ab000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:448 +0x63
bufio.(*Writer).ReadFrom(0xc0002b42c0, 0xd07160, 0xc0003a4340, 0x7f69b4b16938, 0xc0002b42c0, 0x123e501)
        /usr/local/Cellar/go/1.12.5/libexec/src/bufio/bufio.go:722 +0xe5
io.copyBuffer(0xd06ae0, 0xc0002b42c0, 0xd07160, 0xc0003a4340, 0x0, 0x0, 0x0, 0x3, 0x0, 0xc0003b8d01)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:388 +0x2fc
io.Copy(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:364
net/http.(*transferWriter).writeBody(0xc0004465a0, 0xd06ae0, 0xc0002b42c0, 0x2, 0x2)
        /usr/local/Cellar/go/1.12.5/libexec/src/net/http/transfer.go:369 +0x715
net/http.(*Request).write(0xc0002f4100, 0xd06ae0, 0xc0002b42c0, 0x0, 0xc00060c360, 0xc0003a4000, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/net/http/request.go:655 +0x721
net/http.(*persistConn).writeLoop(0xc000288000)
        /usr/local/Cellar/go/1.12.5/libexec/src/net/http/transport.go:1961 +0x1b8
created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.12.5/libexec/src/net/http/transport.go:1358 +0xb0d
```

Setting the `u.Concurrency = 1` prevents the error. Staying below the MultiPart cut-off, which experimentally seems to be 5MB, avoids the problem. I think once that kicks in the concurrency problems start as the Uploader parallelizes the uploads.

If there's anything else I can provide please LMK!

**Comment by colinmarc** [comment]
Hi @PaulMakepeace,

It's hard to say without digging through the s3 client code, but that's probably because `hdfs.Client`s aren't thread safe (and `FileReader`s aren't either). 

Looking at the stack trace, it seems to me it's duck typing to `ReaderAt` and then calling that concurrently (which would work for eg `os.File`).

What you actually want is to have multiple `FileReader`s with different read offsets; I'm unsure of the performance qualities of that on the hdfs side, though. If your files are usually around 67MB, you're probably better off parallelizing at the file level. In any case, it's hard for me to give more specific advice without knowing more about your use case.

I'm going to close this, since the non-thread-safety of clients is well-documented elsewhere. Feel free to chime in if you think that's wrong!
