### ISSUE TITLE
hdfs.New returned nil

### ISSUE THREAD

**Issue by NikolaevAlexandr** [colinmarc/hdfs#222]
Hello, 
I'm trying to execute example:

> client, _ := hdfs.New("testnode:0000")
> fmt.Println("CLIENT IS ",client)
> file, _ := client.Open("/mobydick.txt")
> 
> buf := make([]byte, 59)
> file.ReadAt(buf, 48847)
> 
> fmt.Println(string(buf))
> 
This code write to console this text:

> CLIENT IS  &{0xc0000c0000 <nil>}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x60 pc=0x5ebd6d]
> 
> goroutine 1 [running]:
> github.com/colinmarc/hdfs.(*FileReader).ReadAt(0x0, 0xc00001e100, 0x3b, 0x3b, 0xbecf, 0xc00006b380, 0x0, 0x0)
>         C:/Users/operator/go/src/github.com/colinmarc/hdfs/file_reader.go:195 +0x2d
> main.main()
>         C:/Users/operator/go/src/hdfs_test/main.go:15 +0x151

I imported the env "HADOOP_HOME", but it's not worked.
Please, help me. I'm trying to find information, but not found. 
It's very important for me.

**Comment by NikolaevAlexandr** [comment]
The problem is ignore error while opened file.
