### ISSUE TITLE
Cannot talk to Kerberized DataNode

### ISSUE THREAD

**Issue by davies** [colinmarc/hdfs#258]
When Kerberos is enabled no DataNode, the current client can't talk to it (read  or write).

Do we have a plan to support that?

**Comment by colinmarc** [comment]
Hi @davies,

Kerberized datanodes should currently work. Feel free to reopen if you're having trouble with that.

**Comment by davies** [comment]
@colinmarc Would you point me to the part of code that support it? We still see similar behavior in #248 

We can provide the steps to reproduce the issue, if that's helpful.

**Comment by colinmarc** [comment]
Data transfer encryption was implemented in #236. We test for kerberized datanodes in travis: https://github.com/colinmarc/hdfs/blob/master/travis-setup-cdh6.sh#L160-L176

If you could help me figure out how your configuration is different from the one we test with, maybe that would help narrow it down.

**Comment by tangyoupeng** [comment]
hadoop version: Hadoop 2.8.5
core-site:
```
  <property>
    <name>dfs.data.transfer.protection</name>
    <value>integrity</value>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.suites</name>
    <value/>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.algorithm</name>
    <value/>
  </property>
  <property>
    <name>dfs.encrypt.data.transfer.cipher.suites</name>
    <value/>
  </property>
```
```
2020-12-30 15:27:39,845 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: emr-worker-1.cluster-200517:50010:DataXceiver error processing unknown operation  src: /127.0.0.1:51234 dst: /127.0.0.1:50010
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.doSaslHandshake(SaslDataTransferServer.java:361)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.getSaslStreams(SaslDataTransferServer.java:300)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.receive(SaslDataTransferServer.java:127)
        at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:231)
        at java.lang.Thread.run(Thread.java:748)
2020-12-30 15:28:39,857 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: emr-worker-1.cluster-200517:50010:DataXceiver error processing unknown operation  src: /127.0.0.1:51364 dst: /127.0.0.1:50010
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.doSaslHandshake(SaslDataTransferServer.java:361)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.getSaslStreams(SaslDataTransferServer.java:300)
        at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.receive(SaslDataTransferServer.java:127)
        at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:231)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by colinmarc** [comment]
I just pushed a new release with the data transfer support included. I hadn't done that since this summer - my fault!

Do you mind testing with the new release? I'll reopen if the problem persists or if you were already on latest master.

**Comment by tangyoupeng** [comment]
it works. thank you

**Comment by davies** [comment]
@colinmarc Thanks!
