### ISSUE TITLE
Kerberos private mode is not working on v2.3.0 and v2.2.1

### ISSUE THREAD

**Issue by huanggangfeng** [colinmarc/hdfs#307]
On V2.3.0, read/write will always get the error " read: connection reset by peer",  metadata operations are working well, it also happened on v2.2.1.

The same configuration working well with v2.2.0

Some log messages about data node
```
2022-12-01 15:05:54,443 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: Failed to read expected encryption handshake from client at /172.18.19.23:61366. Perhaps the client is running an older version of Hadoop which does not support encryption
org.apache.hadoop.hdfs.protocol.datatransfer.sasl.InvalidMagicNumberException: Received 1c51ff instead of deadbeef from client.
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.doSaslHandshake(SaslDataTransferServer.java:374)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.getEncryptedStreams(SaslDataTransferServer.java:188)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.SaslDataTransferServer.receive(SaslDataTransferServer.java:120)
	at org.apache.hadoop.hdfs.server.datanode.DataXceiver.run(DataXceiver.java:235)
	at java.lang.Thread.run(Thread.java:748)
```

@colinmarc

**Comment by huanggangfeng** [comment]
I didn't have enough knowledge and time to fix it, but if someone can provide a commit, I can help to do the tests about it.
