### ISSUE TITLE
append call addBlock call failed with ERROR_APPLICATION (org.apache.hadoop.hdfs.server.namenode.NotReplicatedYetException)

### ISSUE THREAD

**Issue by zhaijian** [colinmarc/hdfs#75]
i pulled the code,git version is d9614569203878ff04bb4420b929923949e855fc
when i use append api like:
       
    w, err := client.Append(*hdfsPath)
	if err != nil {
		log.Println("append err", err)
		return
	}
	_, err = w.Write([]byte(mockStr))
	log.Println("write err", err)
	w.Close()

then got err:
     
    addBlock call failed with ERROR_APPLICATION (org.apache.hadoop.hdfs.server.namenode.NotReplicatedYetException
the name node err:

    org.apache.hadoop.hdfs.server.namenode.NotReplicatedYetException: Not replicated yet: /usr/hadoop/test2222.txt
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.analyzeFileState(FSNamesystem.java:3382)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3169)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:641)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:482)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:619)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:962)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2039)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2035)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2033)

but i use the hdfs client,it is ok:
 
     ./hdfs dfs -appendToFile ~/test.111 /usr/hadoop/test2223.txt

the hadoop version is 2.6.0
this issue is same as https://github.com/colinmarc/hdfs/issues/61
any advice? thank you!

**Comment by figoxu** [comment]
How to configure  " Number of Under-Replicated Blocks " on our hdfs apis ?

**Comment by zhaijian** [comment]
when i change the hdfs, it works.

**Comment by wilson001** [comment]
I met the same problem. How did you solve it?
